version: '3.4'

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - '80:7878'

  database:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
